Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@janessym 
janessym
/
cicd-pipeline-train-schedule-canary
Public
forked from linuxacademy/cicd-pipeline-train-schedule-canary
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
cicd-pipeline-train-schedule-canary/train-schedule-kube-canary.yml
@whboyd
whboyd Update train-schedule-kube-canary.yml
Latest commit 0f01d17 on Jun 20, 2019
 History
 1 contributor
49 lines (47 sloc)  929 Bytes

kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-canary
spec:
  type: NodePort
  selector:
    app: train-schedule
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-canary
  labels:
    app: train-schedule
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: train-schedule
      track: canary
  template:
    metadata:
      labels:
        app: train-schedule
        track: canary
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About

